# Generated by Django 4.2.6 on 2024-04-26 03:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255, verbose_name="Text 1")),
                (
                    "image",
                    models.ImageField(upload_to="item_images/", verbose_name="Image 1"),
                ),
            ],
        ),
    ]
