# Generated by Django 4.2.6 on 2024-04-26 04:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.ImageField(upload_to="items/"),
        ),
        migrations.AlterField(
            model_name="item",
            name="text",
            field=models.CharField(max_length=255),
        ),
    ]
