# Generated by Django 4.2.6 on 2024-04-26 04:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_item_image_alter_item_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="items/"),
        ),
        migrations.AlterField(
            model_name="item",
            name="text",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
